networks:
  dust-mite-observability:
    name: dust-mite-observability

services:
  app:
    build:
      context: ../..
      dockerfile: .devcontainer/cpp/Dockerfile
    volumes:
      - ../..:/workspaces/dust-mite:cached
    env_file:
      - path: ../../.env
    # Uncomment to pass through ESP32 device.
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    command: sleep infinity
    networks:
      - dust-mite-observability
