networks:
  dust-mite-observability:
    name: dust-mite-observability

services:
  js:
    build:
      context: ../..
      dockerfile: .devcontainer/js/Dockerfile
    volumes:
      - ../..:/workspaces/dust-mite:cached
    env_file:
      - path: ../../.env
    ports:
      - "5173:5173"
    command: sleep infinity
    networks:
      - dust-mite-observability
      - default
