coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: "flags, diff"
  behavior: default
  require_changes: true

fixes:
  - "/__w/dust-mite/dust-mite/::"
