networks:
  dust-mite-observability:
    name: dust-mite-observability

services:
  cpp:
    build:
      context: ./car
    env_file:
      - path: .env
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    command: sleep infinity
    networks:
      - dust-mite-observability

  python:
    build:
      context: ./controller
      dockerfile: Dockerfile
    env_file:
      - path: .env
    # devices:
    #   - /dev/hidraw4:/dev/hidraw4
    ports:
      - "8765:8765"
    command: sleep infinity
    networks:
      - dust-mite-observability
      - default

  js:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: sleep infinity
    networks:
      - dust-mite-observability
      - default

  jaeger:
    extends:
      file: observability/docker-compose.yml
      service: jaeger
