services:
  cpp:
    # Uncomment to pass through ESP32 device.
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: script -q -c "/home/dustmite/run_cpp.sh" /dev/null

  python:
    command: /home/dustmite/workspace/controller/scripts/run_streamer.sh

  js:
    command: >
      /home/dustmite/workspace/web/scripts/run_dev_server.sh --port 5173 --host
    environment:
      VITE_WS_URL: ws://python:8765
      VITE_OTLP_METRICS_ENDPOINT: http://otel-collector:4318
