apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        customQuery: false
        tags:
          - key: "service.name"
            value: "service_name"
      tracesToProfiles:
        datasourceUid: pyroscope
        profileTypeId: "samples:samples:count:samples:count"
        customQuery: false
        tags:
          - key: "service.name"
            value: "service_name"
