@startuml copper-components
skinparam linetype ortho

package "DualSense" {
	component "Bluetooth" as DS_BT
}

cloud "Wi-Fi" {
	package "Linux PC" {
		component "Controller" as PC_CONTROLLER {
		    component "Bluetooth" as PC_BT
            component "WebSocket\nClient [/]" as PC_CONTROLLER_WS_CLIENT_CONTROL
        }
		component "Streamer" as PC_STREAMER {
            component "WebSocket\nClient [/]" as PC_STREAMER_WS_CLIENT_CONTROL
            component "WebSocket\nClient [/stream]" as PC_STREAMER_WS_CLIENT_STREAM
            component "WebSocket\nClient [/telemetry]" as PC_STREAMER_WS_CLIENT_TELEMETRY
            component "WebSocket\nServer [/]" as PC_STREAMER_WS_SERVER_WEB
        }
		component "Web page" as PC_WEB
	}

	package "ESP32-S3" {
		component "Motor" as ESP_MOTOR
		component "Telemetry" as ESP_TELEMETRY
		component "Camera" as ESP_CAMERA

        component "WebSocket\nServer [/]" as ESP_WS_SERVER_CONTROL
        component "WebSocket\nServer [/stream]" as ESP_WS_SERVER_STREAM
        component "WebSocket\nServer [/telemetry]" as ESP_WS_SERVER_TELEMETRY
	}
}

DS_BT --> PC_BT

PC_STREAMER_WS_SERVER_WEB --> PC_WEB

PC_CONTROLLER_WS_CLIENT_CONTROL --> ESP_WS_SERVER_CONTROL
ESP_WS_SERVER_STREAM --> PC_STREAMER_WS_CLIENT_STREAM
ESP_WS_SERVER_TELEMETRY --> PC_STREAMER_WS_CLIENT_TELEMETRY
PC_STREAMER_WS_CLIENT_CONTROL --> ESP_WS_SERVER_CONTROL

ESP_WS_SERVER_CONTROL --> ESP_MOTOR
ESP_TELEMETRY --> ESP_WS_SERVER_TELEMETRY
ESP_CAMERA --> ESP_WS_SERVER_STREAM

@enduml
