[tool.tox]
legacy_tox_ini = """
    [tox]
    env_list =
        py312

    [testenv]
    deps = -r requirements/dev.txt
    commands = pytest tests/ {posargs}
"""

[tool.mypy]
python_version = "3.12"
files = [
    "src/**/*.py",
    "tests/**/*.py"
]
strict = true

[[tool.mypy.overrides]]
module = "pydualsense"
ignore_missing_imports = true

[tool.ruff]
target-version = "py312"
include = [
    "pyproject.toml",
    "src/**/*.py",
    "tests/**/*.py"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "ISC001",
    "S101",
    "TD002",
    "TD003",
    "FIX002"
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
