name: C++ car

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  build-docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/ltowarek/dust-mite-cpp-devcontainer
        file: ./.devcontainer/cpp/Dockerfile
        push: true

  run-checks:
    needs: build-docker
    permissions:
      contents: read

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ltowarek/dust-mite-cpp-devcontainer
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: ./car

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Activate esp-idf
      run: |
        source $IDF_PATH/export.sh
        echo "$PATH" >> $GITHUB_PATH

    - name: Build
      run: idf.py build
