name: Python controller

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  build-docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/ltowarek/dust-mite-python-devcontainer
        file: ./.devcontainer/python/Dockerfile
        push: true

  run-checks:
    needs: build-docker
    permissions:
      contents: read

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ltowarek/dust-mite-python-devcontainer
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: ./controller

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Activate venv
      run: |
        source /opt/venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Run linters
      run: ./scripts/run_linters.sh --output-format=github
    - name: Run formatter
      run: ./scripts/run_formatter.sh --diff
    - name: Run type checks
      run: ./scripts/run_type_checks.sh
    - name: Run requirements checks
      run: ./scripts/run_requirements_checks.sh

    - name: Run tests
      run: ./scripts/run_tests.sh
