name: Python controller

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install tox
      run: pip install tox
    - name: Create venv
      run: |
        ./scripts/create_venv.sh
        source ./venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
      working-directory: ./controller/

    - name: Run linters
      run: ./scripts/run_linters.sh --output-format=github
      working-directory: ./controller/
    - name: Run formatter
      run: ./scripts/run_formatter.sh --diff
      working-directory: ./controller/
    - name: Run type checks
      run: ./scripts/run_type_checks.sh
      working-directory: ./controller/
    - name: Run requirements checks
      run: ./scripts/run_requirements_checks.sh
      working-directory: ./controller/

    - name: Run tests
      run: ./scripts/run_tests.sh -- --junitxml=./junit/python-controller.xml
      working-directory: ./controller/
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: controller-test-results
        path: ./controller/junit/python-controller.xml
      if: ${{ always() }}
