name: Python controller

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install tox
      run: pip install tox
    - name: Create venv
      run: |
        ./controller/scripts/create_venv.sh
        source ./venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
    - name: Run linters
      run: ./controller/scripts/run_linters.sh --output-format=github
    - name: Run formatter
      run: ./controller/scripts/run_formatter.sh --diff
    - name: Run type checks
      run: ./controller/scripts/run_type_checks.sh
    - name: Run requirements checks
      run: ./controller/scripts/run_requirements_checks.sh
    - name: Run tests
      run: ./controller/scripts/run_tests.sh -- --junitxml=./controller/junit/python-controller.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: python-controller
        path: ./controller/junit/python-controller.xml
      if: ${{ always() }}
